package ecc

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PublicKey) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Curve":
			err = z.Curve.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Curve")
				return
			}
		case "Content":
			err = dc.ReadExactBytes((z.Content)[:])
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PublicKey) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Curve"
	err = en.Append(0x82, 0xa5, 0x43, 0x75, 0x72, 0x76, 0x65)
	if err != nil {
		return
	}
	err = z.Curve.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Curve")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Content)[:])
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PublicKey) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Curve"
	o = append(o, 0x82, 0xa5, 0x43, 0x75, 0x72, 0x76, 0x65)
	o, err = z.Curve.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Curve")
		return
	}
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendBytes(o, (z.Content)[:])
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PublicKey) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Curve":
			bts, err = z.Curve.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Curve")
				return
			}
		case "Content":
			bts, err = msgp.ReadExactBytes(bts, (z.Content)[:])
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PublicKey) Msgsize() (s int) {
	s = 1 + 6 + z.Curve.Msgsize() + 8 + msgp.ArrayHeaderSize + (33 * (msgp.ByteSize))
	return
}
