package math

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Uint256) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Low":
			err = z.Low.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Low")
				return
			}
		case "High":
			err = z.High.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "High")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Uint256) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Low"
	err = en.Append(0x82, 0xa3, 0x4c, 0x6f, 0x77)
	if err != nil {
		return
	}
	err = z.Low.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Low")
		return
	}
	// write "High"
	err = en.Append(0xa4, 0x48, 0x69, 0x67, 0x68)
	if err != nil {
		return
	}
	err = z.High.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "High")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Uint256) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Low"
	o = append(o, 0x82, 0xa3, 0x4c, 0x6f, 0x77)
	o, err = z.Low.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Low")
		return
	}
	// string "High"
	o = append(o, 0xa4, 0x48, 0x69, 0x67, 0x68)
	o, err = z.High.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "High")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Uint256) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Low":
			bts, err = z.Low.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Low")
				return
			}
		case "High":
			bts, err = z.High.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "High")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Uint256) Msgsize() (s int) {
	s = 1 + 4 + z.Low.Msgsize() + 5 + z.High.Msgsize()
	return
}
